name: Build and Deploy - #${{ github.run_number }} | Commit: ${{ github.sha }}

on:
  push:
    branches:
      - main

jobs:
  get-build-number:
    runs-on: ubuntu-latest
    steps:
      - name: Output Run ID
        run: echo "Run ID: ${{ github.run_id }}"

      - name: Output Run Number
        run: echo "Run Number: ${{ github.run_number }}"

      - name: Output Run Attempt
        run: echo "Run Attempt: ${{ github.run_attempt }}"



