name: Build and Deploy - Version:

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # This triggers the workflow on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Job for Version: ${{ github.ref_name }}  # Dynamic version based on tag name
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Build and Test
        run: |
          npm install
          npm run build
