name: Build with Tag

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up build name and number
        run: |
          BUILD_NAME="MyBuild"
          BUILD_NUMBER=${{ github.run_number }}
          echo "Build name: $BUILD_NAME"
          echo "Build number: $BUILD_NUMBER"
          echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

      - name: Configure Git user
        run: |
          git config --global user.name "Veena2002"
          git config --global user.email "nagaveenav@datatemplate.com"

      - name: Tag build
        run: |
          git tag -a "${{ env.BUILD_NAME }}-${{ env.BUILD_NUMBER }}" -m "Build ${{ env.BUILD_NAME }}-${{ env.BUILD_NUMBER }}"
          git push origin "${{ env.BUILD_NAME }}-${{ env.BUILD_NUMBER }}"

      - name: Upload build details
        uses: actions/upload-artifact@v3
        with:
          name: build-details
          path: ${{ env.BUILD_NAME }}-${{ env.BUILD_NUMBER }}
          retention-days: 1
