name: Build and Deploy with Tagging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Application
        run: echo "Building application..."

      - name: Create and Push Tag
        run: |
          # Set a tag name, using the run number
          TAG_NAME="build-${{ github.run_number }}"
          echo "Creating tag ${TAG_NAME}"
          
          # Create the tag
          git tag $TAG_NAME

          # Push the tag to GitHub
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
